#!/bin/bash

# Product Features (1-27)
mv MISSING_FEATURES_01_MOBILE_APPS.md PRODUCT_MOBILE_APPS.md 2>/dev/null
mv MISSING_FEATURES_02_TELEMEDICINE.md PRODUCT_TELEMEDICINE.md 2>/dev/null
mv MISSING_FEATURES_03_FAMILY_HEALTH.md PRODUCT_FAMILY_HEALTH_RECORDS.md 2>/dev/null
mv MISSING_FEATURES_04_WEARABLES.md PRODUCT_WEARABLES_INTEGRATION.md 2>/dev/null
mv MISSING_FEATURES_05_ADVANCED_ANALYTICS.md PRODUCT_ADVANCED_ANALYTICS.md 2>/dev/null
mv MISSING_FEATURES_06_COMMUNITY_FORUMS.md PRODUCT_COMMUNITY_FORUMS.md 2>/dev/null
mv MISSING_FEATURES_07_EDUCATIONAL_CONTENT.md PRODUCT_EDUCATIONAL_CONTENT.md 2>/dev/null
mv MISSING_FEATURES_08_PROVIDER_PORTAL.md PRODUCT_PROVIDER_PORTAL.md 2>/dev/null
mv MISSING_FEATURES_09_CLINICAL_DECISION_SUPPORT.md PRODUCT_CLINICAL_DECISION_SUPPORT.md 2>/dev/null
mv MISSING_FEATURES_10_PRESCRIPTION_MANAGEMENT.md PRODUCT_PRESCRIPTION_MANAGEMENT.md 2>/dev/null
mv MISSING_FEATURES_11_INSURANCE_CLAIMS.md PRODUCT_INSURANCE_CLAIMS.md 2>/dev/null
mv MISSING_FEATURES_12_CLINICAL_TRIALS.md PRODUCT_CLINICAL_TRIALS_MATCHING.md 2>/dev/null
mv MISSING_FEATURES_13_SECOND_OPINION.md PRODUCT_SECOND_OPINION_SERVICE.md 2>/dev/null
mv MISSING_FEATURES_14_HEALTH_RECORDS.md PRODUCT_HEALTH_RECORDS_EXCHANGE.md 2>/dev/null
mv MISSING_FEATURES_15_CAREGIVER_PORTAL.md PRODUCT_CAREGIVER_PORTAL.md 2>/dev/null
mv MISSING_FEATURES_16_MULTI_LANGUAGE.md PRODUCT_MULTI_LANGUAGE_SUPPORT.md 2>/dev/null
mv MISSING_FEATURES_17_ACCESSIBILITY.md PRODUCT_ACCESSIBILITY_FEATURES.md 2>/dev/null
mv MISSING_FEATURES_18_REPORTING.md PRODUCT_COMPLIANCE_REPORTING.md 2>/dev/null
mv MISSING_FEATURES_19_AI_ASSISTANT.md PRODUCT_AI_HEALTH_ASSISTANT.md 2>/dev/null
mv MISSING_FEATURES_20_BLOCKCHAIN.md PRODUCT_BLOCKCHAIN_DATA_INTEGRITY.md 2>/dev/null

# Research Platform (21A-21C)
mv MISSING_FEATURES_21A1_RESEARCH_PLATFORM_INTRO.md RESEARCH_PLATFORM_OVERVIEW.md 2>/dev/null
mv MISSING_FEATURES_21A2_PATIENT_REGISTRY.md RESEARCH_PATIENT_REGISTRY.md 2>/dev/null
mv MISSING_FEATURES_21A3_NATURAL_HISTORY.md RESEARCH_NATURAL_HISTORY_STUDIES.md 2>/dev/null
mv MISSING_FEATURES_21A4_CONSENT_MANAGEMENT.md RESEARCH_CONSENT_MANAGEMENT.md 2>/dev/null
mv MISSING_FEATURES_21A5_DASHBOARDS.md RESEARCH_DASHBOARDS_ANALYTICS.md 2>/dev/null
mv MISSING_FEATURES_21B1_RWE_GENERATION.md RESEARCH_REAL_WORLD_EVIDENCE.md 2>/dev/null
mv MISSING_FEATURES_21B2_PATIENT_REPORTED_OUTCOMES.md RESEARCH_PATIENT_OUTCOMES.md 2>/dev/null
mv MISSING_FEATURES_21B3_WEARABLES_REMOTE_MONITORING.md RESEARCH_WEARABLES_MONITORING.md 2>/dev/null
mv MISSING_FEATURES_21C1_MULTI_SITE_COLLABORATION.md RESEARCH_MULTI_SITE_COLLABORATION.md 2>/dev/null
mv MISSING_FEATURES_21C2_EXTERNAL_REGISTRY_INTEGRATION.md RESEARCH_EXTERNAL_REGISTRIES.md 2>/dev/null
mv MISSING_FEATURES_21C3_DATA_STANDARDIZATION.md RESEARCH_DATA_STANDARDIZATION.md 2>/dev/null

# Infrastructure & Scale (22-26)
mv MISSING_FEATURES_22_SECURITY_FRAUD.md INFRASTRUCTURE_SECURITY_FRAUD_PREVENTION.md 2>/dev/null
mv MISSING_FEATURES_23_GLOBAL_EXPANSION.md INFRASTRUCTURE_GLOBAL_EXPANSION.md 2>/dev/null
mv MISSING_FEATURES_24_INFRASTRUCTURE.md INFRASTRUCTURE_PLATFORM_SCALABILITY.md 2>/dev/null
mv MISSING_FEATURES_25_PATIENT_PAYMENT.md PRODUCT_PATIENT_PAYMENT_PORTAL.md 2>/dev/null
mv MISSING_FEATURES_26_ADVANCED_ANALYTICS.md PRODUCT_PARTNER_ADVANCED_ANALYTICS.md 2>/dev/null

# Summary Documents
mv MISSING_FEATURES_27-38_SUMMARY.md PRODUCT_FEATURES_27_38_SUMMARY.md 2>/dev/null

# Operations (39-46)
mv MISSING_FEATURES_39_REVENUE_CYCLE_MANAGEMENT.md OPERATIONS_REVENUE_CYCLE_MANAGEMENT.md 2>/dev/null
mv MISSING_FEATURES_40_CUSTOMER_SUPPORT.md OPERATIONS_CUSTOMER_SUPPORT.md 2>/dev/null
mv MISSING_FEATURES_41-46_OPERATIONS_PARTNERSHIPS.md OPERATIONS_INFRASTRUCTURE_41_46.md 2>/dev/null

# Business Operations (47-53)
mv MISSING_FEATURES_47_SALES_BIZ_DEV.md BUSINESS_SALES_BIZ_DEV.md 2>/dev/null
mv MISSING_FEATURES_48_MARKETING_GROWTH.md BUSINESS_MARKETING_GROWTH.md 2>/dev/null
mv MISSING_FEATURES_49-53_BUSINESS_OPS.md BUSINESS_OPERATIONS_49_53.md 2>/dev/null

# Master Index
mv MISSING_FEATURES_MASTER_INDEX.md MASTER_FEATURE_INDEX.md 2>/dev/null

echo "All files renamed successfully!"
